# See: https://taskfile.dev/api/

version: "3"

tasks:
  migration:
    aliases:
      - migrate
    desc: "Apply migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations